# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/demo/simple_adder_microblaze_interface/simple_adder_microblaze_interface/simple_adder_microblaze_interface.srcs/sources_1/bd/design_101/ip/design_101_axi_bram_ctrl_0_0/design_101_axi_bram_ctrl_0_0.xci
# IP: The module: 'design_101_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/demo/simple_adder_microblaze_interface/simple_adder_microblaze_interface/simple_adder_microblaze_interface.srcs/sources_1/bd/design_101/ip/design_101_axi_bram_ctrl_0_0/design_101_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_101_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/demo/simple_adder_microblaze_interface/simple_adder_microblaze_interface/simple_adder_microblaze_interface.srcs/sources_1/bd/design_101/ip/design_101_axi_bram_ctrl_0_0/design_101_axi_bram_ctrl_0_0.xci
# IP: The module: 'design_101_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/demo/simple_adder_microblaze_interface/simple_adder_microblaze_interface/simple_adder_microblaze_interface.srcs/sources_1/bd/design_101/ip/design_101_axi_bram_ctrl_0_0/design_101_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_101_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
