# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_101/design_101.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101 || ORIG_REF_NAME==design_101} -quiet] -quiet

# IP: bd/design_101/ip/design_101_microblaze_0_0/design_101_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_microblaze_0_0 || ORIG_REF_NAME==design_101_microblaze_0_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_dlmb_v10_0/design_101_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_dlmb_v10_0 || ORIG_REF_NAME==design_101_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_ilmb_v10_0/design_101_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_ilmb_v10_0 || ORIG_REF_NAME==design_101_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_dlmb_bram_if_cntlr_0/design_101_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_101_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_ilmb_bram_if_cntlr_0/design_101_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_101_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_lmb_bram_0/design_101_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_lmb_bram_0 || ORIG_REF_NAME==design_101_lmb_bram_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_mdm_1_0/design_101_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_mdm_1_0 || ORIG_REF_NAME==design_101_mdm_1_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_clk_wiz_1_0/design_101_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_clk_wiz_1_0 || ORIG_REF_NAME==design_101_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_rst_clk_wiz_1_100M_0/design_101_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_101_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_axi_bram_ctrl_0_0/design_101_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_101_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_xbar_0/design_101_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_xbar_0 || ORIG_REF_NAME==design_101_xbar_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_auto_pc_0/design_101_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_auto_pc_0 || ORIG_REF_NAME==design_101_auto_pc_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_axi_mem_intercon_0/design_101_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_axi_mem_intercon_0 || ORIG_REF_NAME==design_101_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_axi_bram_ctrl_0_bram_0/design_101_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==design_101_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_myip_simple_adder_v1_0_0/design_101_myip_simple_adder_v1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_myip_simple_adder_v1_0_0 || ORIG_REF_NAME==design_101_myip_simple_adder_v1_0_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_axi_uartlite_0_0/design_101_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_axi_uartlite_0_0 || ORIG_REF_NAME==design_101_axi_uartlite_0_0} -quiet] -quiet

# XDC: bd/design_101/design_101_ooc.xdc
